version: '3'
services:
  web:
    container_name: design_parttern_nginx
    image: 'nginx:latest'
    ports:
      - '10182:80'
    volumes:
      - './.docker/nginx/conf.d/:/etc/nginx/conf.d/'
      - '.:/var/www/'
  php:
    container_name: design_parttern_php
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - '.:/var/www/'
  mysql:
    container_name: design_parttern_mysql
    image: 'mysql:oracle'
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - './.docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf'
      - './.docker/mysql/charset.cnf:/etc/mysql/conf.d/charset.cnf'
      - './.db:/var/lib/mysql'
    ports:
      - '3382:3306'
